# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58731dc9fde29e5f5b45f8ed7f9433ac56fd8d54acbfc28f476a8a2d0129421467407e2cd3e9c2681fc9aca5172b31a34a71d5fc66e949080ab8e11ee85b5182

test:
  secret_key_base: b12bb34897f513d974c96c7371b2963b98bcfbdc53501dc4c00da884847432da9a00ec91683987ed3e86f1eaefbe03e6a4340f3cf00685fbbc738ef6db8db679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
